### ISSUE TITLE
Expose Argo CDR: Workflow

### ISSUE THREAD

**Issue by themadmrj** [devtron-labs/devtron#1275]
Is it possible to create a Workflow kind in the Devtron dashboard? The Devtron architecture stack already leverages Argo Workflow and I'm trying to figure out how to do that. Would a rawYaml work? I'm basically looking to create this in Devtron to avoid interacting directly with Argo:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-  # Name of this Workflow
spec:
  entrypoint: whalesay        # Defines "whalesay" as the "main" template
  templates:
  - name: whalesay            # Defining the "whalesay" template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]   # This template runs "cowsay" in the "whalesay" image with arguments "hello world"
```
Devtron currently allows creating Jobs and Cronjobs out of the box, but I need a way to chain multiple jobs and more specifically A -> B -> [C, D, E] where C, D, E run in parallel and depend on A and B.

Here's a bit more information. I'm looking for a way to create the following Workflow in Devtron:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow
  namespace: dev
spec:
  entrypoint: wf
  templates:
  - name: wf
    dag:
      tasks:
      - name: transform
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/myproject/argo-test:latest
      - name: job2
        dependencies: [transform]
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/myproject/argo-test2a:latest
      - name: job3
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/myproject/argo-test2b:latest
  - name: wf-template
    inputs:
      parameters:
        - name: image
    container:
      image: {{inputs.parameters.image}}
```
As you can see, there will be multiple jobs with dependencies (steps instead of dag would also work) and each job will have it's own image, matching a distinct repository.

**Comment by jonasschalck** [comment]
Since I can't edit, here's a bit more information. I'm looking for a way to create the following Workflow in Devtron:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow
  namespace: dev
spec:
  entrypoint: wf
  templates:
  - name: wf
    dag:
      tasks:
      - name: transform
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/tall-ridge/argo-test:latest
      - name: job2
        dependencies: [transform]
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/tall-ridge/argo-test2a:latest
      - name: job3
        template: wf-template
        arguments:
          parameters:
            - name: image
              value: gcr.io/tall-ridge/argo-test2b:latest
  - name: wf-template
    inputs:
      parameters:
        - name: image
    container:
      image: {{inputs.parameters.image}}
```
As you can see, there will be multiple jobs with dependencies (steps instead of dag would also work) and each job will have it's own image, matching a distinct repository.
