### ISSUE TITLE
Enable workflows garbage collector

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1708]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Workflows keep accumulating in cluster and no garbage collection is enabled for them which results into more than required load for workflow controller

**To Reproduce**

1. Create a build pipeline
2. Trigger the build
3. It's workflow will still be there even after a month or 6 months

**Expected behavior**

Grabage collection should automatically clear older workflows

**Current behavior** 

Garbage collection is not enabled

** What can be done **
We can add this to all the workflows we create which will enable garbage collection
```
spec:
  ttlStrategy:
    secondsAfterCompletion: 10 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 5     # Time to live after workflow is successful
    secondsAfterFailure: 5     # Time to live after workflow fails
  ```
