### ISSUE TITLE
Failed to pull image with 401 Unauthorized when deployed to AKS + Azure Container Registry

### ISSUE THREAD

**Issue by scheung38** [devtron-labs/devtron#1930]
**Describe the bug**
After successful Django app CI build, not able to deploy to AKS cluster (ACR)

**To Reproduce**

Deployed Devtron via helm in same AKS cluster

https://kubernetes.default.svc

using the default_cluster that came with it, or we are supposed to define a new 'Add cluster' with the output from 
the command to provide the Server URL and Bearer token via?:

curl -O https://raw.githubusercontent.com/devtron-labs/utilities/main/kubeconfig-exporter/kubernetes_export_sa.sh && bash kubernetes_export_sa.sh cd-user devtroncd https://raw.githubusercontent.com/devtron-labs/utilities/main/kubeconfig-exporter/clusterrole.yaml

https://docs.devtron.ai/devtron/setup/global-configurations/cluster-and-environments

This is portion of the Deployment Template:

```
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  className: ""
  enabled: true
  hosts:
    - host: ""
      pathType: ImplementationSpecific
      paths:
        - /arthur-app(/|$)(.*)
    - host: chart-example2.local
      pathType: ImplementationSpecific
      paths:
        - /example2
        - /example2/healthz
  labels: {}
  tls: []
```

From Devtron - App Details - Events:

Successfully assigned xxx-nonprod/xxxx-nonprod-58995fc6b8-2mbln to aks-agentpool-84246901-vmss000003

Pulling image "xxx.azurecr.io/xxxacr.azurecr.io:cb80f760-2-2"
Failed to pull imagxe "xxx.azurecr.io/xxxacr.azurecr.io:cb80f760-2-2": rpc error: code = Unknown desc = failed to pull and unpack image "xxx.azurecr.io/xxxacr.azurecr.io:cb80f760-2-2": failed to resolve reference "xxxr.azurecr.io/xxxacr.azurecr.io:cb80f760-2-2": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized

Error: ErrImagePull

Back-off pulling image "xxx.azurecr.io/xxxacr.azurecr.io:cb80f760-2-2"

Error: ImagePullBackOff

<br class="Apple-interchange-newline">

These are my roles:

`az role assignment list --assignee $AZURE_CLIENT_ID -o table
`

![Screenshot 2022-06-26 at 00 30 19](https://user-images.githubusercontent.com/1273014/175793479-d27ce10b-114c-4393-bf14-2466c092838f.png)

Do we need to setup tls cert or is that done for us in Devtron?

**Logs**
 
```
Paste any relevant application logs here.
```
EDIT: I feel this is related to secret not setup? But not sure where Devtron is looking for that if kind:Secret was not defined?

AB#343
