### ISSUE TITLE
Add SSO GitLab provider support

### ISSUE THREAD

**Issue by mateuszklysz** [devtron-labs/devtron#2062]
# Summary

Add additional support for SSO GitLab provider in SSO Login Services

# Motivation

Since Dex supports GitLab, it would be nice to handle this from the dashboard. Many teams use GitLab and such an option should also appear in Devtron.

# Proposal

Currently, OIDC has a hardcoded ID on `google` and this cannot be edited. 
The best solution would be to add a separate option with a GitLab icon, as it is solved in the GitHub option.

<img width="904" alt="Screenshot 2022-07-20 at 08 55 28" src="https://user-images.githubusercontent.com/61278775/179916936-77ff8d26-501a-43c2-84e4-280da66e4778.png">

_Configuration example:_
```
config:
  type: gitlab 
  name: GitLab
  id: gitlab
  config:
    clientID: $GITLAB_CLIENT_ID                                                    
    clientSecret: $GITLAB_CLIENT_SECRET                                                              
    baseURL: https://gitlab.com                                                                                                                            
    redirectURI: http://devtron.yourdomain.com/orchestrator/api/dex/callback
    groups:
      - my-group
      - my-another-group
 ```

AB#82
