### ISSUE TITLE
Feature: Use cluster-name instead of server url in Argocd application objects

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#2378]
### 🔖 Feature description

Use cluster `destination.name` instead of `destination.server` in Argocd application object to extend cluster portability.

### 🎤 Pitch

If user decides to change the cluster/server url, they currently need to update it at all the application object as well. If we use `destination.name` in application object, they will only need to update the cluster information.

### ✌️ Solution

Present
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
```

Proposed
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    name: demo-cluster
    namespace: guestbook
```

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#551
