### ISSUE TITLE
Bug: Build Logs not Streaming in KIND cluster (END OF STREAM)

### ISSUE THREAD

**Issue by rhythmbhiwani** [devtron-labs/devtron#3636]
### 📜 Description

The build logs on Devtron are not streaming as expected. This bug hampers the real-time visibility into the build process.

### 👟 Reproduction steps

1. Setup a kind cluster on ubuntu machine using this kind-config
```
// kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
```
`kind create cluster --config=kind-config.yaml`

2. Install devtron using this command
`helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd --set installer.modules={cicd} --set components.devtron.service.type=NodePort --set minio.enabled=true --set argo-cd.enabled=true`

3. Setup Ingress-nginx, cert-manager and clustterissuer using these.
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml`

`kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml`
```
// cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
```

4. Setup ingress on devtron
`kubectl patch -n devtroncd svc devtron-service -p '{"spec": {"ports": [{"port": 80,"targetPort": "devtron","protocol": "TCP","name": "devtron"}],"type": "ClusterIP","selector": {"app": "devtron"}}}'`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /dashboard
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: devtron
    release: devtron
  name: devtron-ingress
  namespace: devtroncd
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - example.domain.com
    secretName: tls-secret
  rules:
  - host: example.domain.com
    http:
      paths:
      - path: /orchestrator
        backend:
            service:
              name: devtron-service
              port:
                number: 80
        pathType: ImplementationSpecific
      - path: /dashboard
        backend:
          service:
            name: devtron-service
            port:
              number: 80
        pathType: ImplementationSpecific
      - backend:
          service:
            name: devtron-service
            port:
              number: 80
        path: /grafana
        pathType: ImplementationSpecific
```

5. Now access devtron on url, create a build pipeline, check the build logs

### 👍 Expected behavior

The logs should stream in real-time, and keep updating as new logs come in.

Also one more issue I found (but it was a bit random). That after successful deployment, when I check logs of the container, the last line of logs starts printing repetedly for no reason.

### 👎 Actual Behavior

The logs come and instead of updating real-time, it just ends with a `END OF STREAM` message. Then we have to refresh the page to see updated logs everytime.

### ☸ Kubernetes version

Kind Cluster 1.27.3 on Ubuntu 22.04 with 4 CPU and 24 GB RAM

### Cloud provider

<details>
Oracle Cloud Infrastructre and DigitalOcean
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Chrome 114.0.5735.198
No customization

### ✅ Proposed Solution

Seems something specific to kind, maybe some internal issue, or a configuration issue, I did not faced this issue on Managed Kubernetes Cluster

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)
