### ISSUE TITLE
Bug: Gitops replicas sync into the deployment/rollout on commits made to same repo + same folder

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#3863]
### 📜 Description

If an app is deployed in multiple environments using same chart version, the deployment in one of the environments also triggers the sync in all other environments as well. 

Refer the following configurations, where the app1 is deployed in dev and stage environments using the same chart version 4.17.1 in which case Argocd repo-server will always initiate a manifest generation as soon as commit is made to any file within `reference-chart_4-17-0/4.17.1` directory be it in  `_env1-dev.yaml` or  `_env1-stage.yaml`

app1-dev
```
  source:
    helm:
      valueFiles:
        - _env1-dev.yaml
    path: reference-chart_4-17-0/4.17.1
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
```

app1-stage
```
  source:
    helm:
      valueFiles:
        - _env1-stage.yaml
    path: reference-chart_4-17-0/4.17.1
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
```

This should not always create issue unless there is a huge difference in HPA's desired replica and the spec/replicas set in the gitops manifest, which is a valid use case and needs to be handled.

### 👟 Reproduction steps

Deploy an application in two environments (dev and stage) with same chart version (eg 4.17.1). In stage deploy with HPA enabled (min:1 and max:5, replicas:1 ) with low threshold (so as to trigger scaleup), as soon as the HPA desired replicas increases post deployment, change some configurations in dev environment and redeploy (commit to gitops).

### 👍 Expected behavior

The sync should not reset the spec/replicas to 1 in case the replica count is controlled by the HPA.

### 👎 Actual Behavior

The sync will set the spec/replicas to 1 for some time and then the HPA scales it back to original desired replicas.

### ☸ Kubernetes version

The issue happens on all K8s versions.

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

**Short term solution:**
In all the argocd application objects, include the following configuration to ignore the diff in spec/replicas while syncing changes:    
```    
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas
 ```
 
 Set the following syncOptions to enable ignoreDifferences configurations only when HPA/Keda HPA is enabled.
 ```
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true     ##When syncing changes, respect fields ignored by the ignoreDifferences configuration
```
Reference: https://argo-cd.readthedocs.io/en/stable/operator-manual/application.yaml

**Long term solution:**
A new folder structure needs to be introduced that creates separate folders for each environment in the gitops repo. This needs to be implemented in a trolling fashion.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5339
