### ISSUE TITLE
Bug: Helm Template sometimes display completely wrong deployment in Manifest Output

### ISSUE THREAD

**Issue by VladoPortos** [devtron-labs/devtron#4107]
### 📜 Description

I have set OCI registry for helm chart, chart is downloaded and presented into chart store ( So far so good )

I click on the chart, and go "configure and deploy", fill in app name, project, environment (I did not change anything in default values.yaml), then I press "Manifest output" and I get nice rendered helm template. (So far so good)

I create a "Preset values", change couple of options just to test. and when I click now on "Manifest output" I get this instead of my rendered template: 
(It come out of nowhere, nothing like that is anywhere in my chart)

```
---
# Source: cluster-autoscaler/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: "vlado1"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.29.2"
  name: vlado1-aws-cluster-autoscaler
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "vlado1"
      app.kubernetes.io/name: "aws-cluster-autoscaler"
  
  maxUnavailable: 1
---
# Source: cluster-autoscaler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "vlado1"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.29.2"
  name: vlado1-aws-cluster-autoscaler
  namespace: default
automountServiceAccountToken: true
---
# Source: cluster-autoscaler/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: "vlado1"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.29.2"
  name: vlado1-aws-cluster-autoscaler
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - endpoints
    verbs:
      - create
      - patch
  - apiGroups:
    - ""
    resources:
    - pods/eviction
    verbs:
    - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    resourceNames:
      - cluster-autoscaler
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
    - watch
    - list
    - get
    - update
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - watch
      - list
      - get
  - apiGroups:
    - batch
    resources:
      - jobs
      - cronjobs
      - 
    ```

![A](https://github.com/devtron-labs/devtron/assets/11806871/68c6e845-acdb-4946-b0be-48560378f149)
![B](https://github.com/devtron-labs/devtron/assets/11806871/3cfa7f4d-075e-40d5-a70e-4a09e670d243)
![C](https://github.com/devtron-labs/devtron/assets/11806871/d57e1d4c-1155-44a5-9255-3d567afefd80)
![D](https://github.com/devtron-labs/devtron/assets/11806871/d0e7bd97-98bb-4116-bfe2-f2509b8be055)
![E](https://github.com/devtron-labs/devtron/assets/11806871/9698a88d-c9a1-473a-a805-8d00dbb951db)
![F](https://github.com/devtron-labs/devtron/assets/11806871/9626d870-16fa-40de-a8ff-184e4ce6280e)
![G](https://github.com/devtron-labs/devtron/assets/11806871/291c5349-ff86-4e96-a51b-3dc41e151975)
![H](https://github.com/devtron-labs/devtron/assets/11806871/26790a21-5fdc-4075-8870-40f30250f253)

### 👟 Reproduction steps

See description

### 👍 Expected behavior

It should render the correct template.

### 👎 Actual Behavior

Render random AWS related template.

### ☸ Kubernetes version

Client Version: v1.27.6+k3s1
Kustomize Version: v5.0.1
Server Version: v1.27.6+k3s1

### Cloud provider

<details>
None, self hosted
</details>

### 🌍 Browser

Opera

### 🧱 Your Environment

No customization

### ✅ Proposed Solution

No idea where it comes from, clearly on background it confuse the output. It does not seems to have effect on "deploy" button, at least so far it always deployed my helm chart and not that AWS one.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)
