### ISSUE TITLE
Feature: Integrate ConfigMap Support into CI-Runner Workflow/Job

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#4659]
### 🔖 Feature description

We want to mount the config map at `/usr/local/share/ca-certificates/ca.crt` and execute `update-ca-certificates` beforehand (Before cloning the git repo). This ensures that the custom certificate is validated, enabling seamless cloning of the repository without encountering any issues.

### 🎤 Pitch / Usecases

```
apiVersion: v1
data:
  ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDnzCCAoegAwIBAgIUfd9jaIjo2JCYYedUbfA8aecTdIswDQYJKoZIhvcNAQEL
      EXSKoI4rLM7WLTYdljGryKXnuR4hZFGB8Lr664l0z816DSyeFqdyEbIHaA4upbB8
      G9ghU5ZeBcYAgpZEjfTqWYmceQ==
      -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: self-signed-cert
```

add the config map in  ci runer pod `usr/local/share/ca-certificates` path 
```
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates/
              name: self-signed-cert-volume
      volumes:
        - configMap:
            defaultMode: 420
            name: self-signed-cert
          name: self-signed-cert-volume

```
and run this command before cloaning   the git repo `update-ca-certificates`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8432
