### ISSUE TITLE
Bug: OOMKill on Housekeeping Job

### ISSUE THREAD

**Issue by antikilahdjs** [devtron-labs/devtron#4747]
### 📜 Description

When install the devtron the job to cleanup (Housekeeping) getting a OOMKill due the resources allocated is to low

![image](https://github.com/devtron-labs/devtron/assets/33559260/a5c7ac38-c5a3-4d22-9ead-94adf7849c42)

I cannot change it using the helm values and so on because the housekeep is downloaded during the install. I am tried put the configuration on override but after check deeply I saw that came from git and the override does not works

### 👟 Reproduction steps

1. Just install the devtron using the official helm charts

### 👍 Expected behavior

Works with more resources for housekeeping

### 👎 Actual Behavior

OOMKill

```yaml
 limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
```

### ☸ Kubernetes version

On-Premise 1.23.6

### Cloud provider

<details>
Not using cloud in this environment
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

Just increase the resource or create some way to change it using the helm charts instead downloading automatically during the install

```yaml
 limits:
      cpu: 2 -->> or more
      memory: 512Mi --->>> or more
    requests:
      cpu: 50m
      memory: 50Mi
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8787
