### ISSUE TITLE
Feature: Deployment Template should allow injection of pre-defined manifests

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#519]
# Summary

Currently Deployment Template supports a section called `rawYaml` where users can add their yaml configuration manually to deploy resources not defined in Devtron charts. Although this feature is useful, but becomes a hassle when a user has to inject many such yaml manifests. Especially at an organization level, when there are certain manifests which has to be deployed for all the services (e.g. Istio/Ambassador supported manifests), it becomes really messy and error-prone to keep copy-pasting these yamls for each service.

# Motivation

As explained above, we would like to deploy certain manifests which are nearly common for all services in an organization.

# Proposal

Super-Admins should be able to define certain manifests (in Global configurations) which can be injected to each Deployment Template. Once the manifests are defined, they should be made available to be configured in Deployment Template. Additionally, `rawYaml` can be made as a sub-section of (separate UI panel inside) Deployment Template, and under this sub-section user can pick and choose which manifest should be deployed as part of the Deployment Template. We can also templatize these manifests, and can render them in the `rawYaml` sub-section (if the user selects it), by feeding values from the main Deployment Template section.

For example, we define a manifest/template in the Global Configurations section like this:
```yaml
- apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
      name: <service.name>-api-mapping
  spec:
      prefix: /<service.name>/
      service: <service.name>.<environment_overrides.name>:<ContainerPort[0].servicePort>
```

Now if the user selects this template, it will be rendered as (assuming service.name: `demo`, env: `dev` and servicePort: `80`):
```yaml
rawYaml:
- apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
      name: demo-api-mapping
  spec:
      prefix: /demo/
      service: demo.dev:80
```

AB#314
