### ISSUE TITLE
Support setting Host URL, configure gitops, and container registry from helm.

### ISSUE THREAD

**Issue by ruckc** [devtron-labs/devtron#545]
# Summary

When initially deploying devtron with the helm chart, the Host URL, gitops configuration, and container registry are unconfigured.

# Motivation

I want to declaratively configure devtron, which requires zero human interaction to have setup.

# Proposal

Ideally these should be enumerated out in the operator's default values.yaml.

**Comment by xuanyuanaosheng** [comment]
@ruckc   Support it.   I have installed devtron using helm.   I login the devtron using admin, but I can not configure the devtron.

The error is : 
```
Not authorized
Looks like you don’t have access to information on this page. Please contact your manager to request access.
```

![image](https://user-images.githubusercontent.com/4197714/129013767-33fc5614-5114-47f4-a559-b296edb94c17.png)

**Comment by nishant-d** [comment]
looks like migration job failed.  can you please share logs of migration job. 
you can get logs by running the command 
```kubectl logs -l job-name=postgresql-migrate-casbin -n devtroncd```

**Comment by xuanyuanaosheng** [comment]
@nishant-d 

The job status
```
kubectl get job -n devtroncd
NAME                            COMPLETIONS   DURATION   AGE
app-sync-cronjob-1628593200     1/1           7m38s      2d18h
app-sync-cronjob-1628679600     1/1           39m        42h
app-sync-cronjob-1628766000     1/1           24m        18h
app-sync-job                    1/1           1s         4d2h
devtron-minio-make-bucket-job   1/1           51m        6d20h
postgresql-migrate-casbin       0/1           2m13s      2m13s
postgresql-migrate-devtron      1/1           21m        4d2h
postgresql-migrate-gitsensor    1/1           16s        39m
```


The log is:
```
{"level":"info","ts":1628832658.7622538,"caller":"migrator/GitUtil.go:97","msg":"git checkout ","url":"https://hub.fastgit.org/devtron-labs/devtron.git","dir":"app","branch":"main"}

starting migration

valid git config found

&{ /tmp/ https://hub.fastgit.org/devtron-labs/devtron.git 4ed6cdfcf6f13a93eb0c3c58d8b4f13292856960 main scripts/casbin/}

valid migrate config found

&{postgres://postgres:M2tVVTV6SWpxMURLWkZNalBZcXNhSU1JeU80PQo@postgresql-postgresql.devtroncd:5432/casbin?sslmode=disable 0 postgres postgres M2tVVTV6SWpxMURLWkZNalBZcXNhSU1JeU80PQo postgresql-postgresql.devtroncd 5432 casbin}

migrate util created

app initialised

{"level":"info","ts":1628832731.4168468,"caller":"migrator/GitUtil.go:108","msg":"cloned ","dir":"/tmp/app","source":"https://hub.fastgit.org/devtron-labs/devtron.git"}

{"level":"info","ts":1628832731.4169106,"caller":"migrator/GitUtil.go:119","msg":"checking out hash ","hash":"4ed6cdfcf6f13a93eb0c3c58d8b4f13292856960"}

checkout /tmp/app

{"level":"info","ts":1628832734.8270278,"caller":"migrator/MigrateUtil.go:60","msg":"migrating from","location":"file:///tmp/app/scripts/casbin"}

{"level":"error","ts":1628832734.8430302,"caller":"migrator/MigrateUtil.go:73","msg":"dirty db state found will not apply changes. please clean db manually first","CurrentVersion":1,"stacktrace":"main.MigrateUtil.migrateUp\n\t/migrator/MigrateUtil.go:73\nmain.MigrateUtil.Migrate\n\t/migrator/MigrateUtil.go:55\nmain.main\n\t/migrator/App.go:20\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}

2021/08/13 05:32:14 dirty db found

```

![image](https://user-images.githubusercontent.com/4197714/129309752-14c18312-ba0a-4d1a-af51-13f2c7603ef5.png)


Could you please give some advice?

**Comment by prakarsh-dt** [comment]
Hi @xuanyuanaosheng ,

Since the casbin migration job failed, the default policies for super-admin were not created. Please follow the steps below to re-run it:

1. Exec inside the postgresql pod and login postgres:
```
kubectl exec -it postgresql-postgresql-0 -n devtroncd sh
psql -U postgres
```
Enter the postgres password set by you or if you did not set it up yourself, you would find it in the secret `devtron-secret` in base64 encoded format, please decode it before using.
```kubectl get secret -n devtroncd devtronn-secret```

2. Once logged in to the postgres, connect to casbin DB and remove dirty flag from the casbin db:
```
\c casbin
update schema_migrations set dirty=false;
```

3. Delete the migration job and rerun it:
```
kubectl delete job postgresql-migrate-casbin -n devtroncd
```
Apply the following manifest in the namespace devtroncd to rerun the migration (If you're located in a region where github.com is not accessible, please change the `GIT_REPO_URL` to your corresponding forked repo URL)
```
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-casbin
spec:
  template:
    spec:
      containers:
      - name: postgresql-migrate-casbin
        image: quay.io/devtron/migrator:6687f572-133-2208
        env:
        - name: SCRIPT_LOCATION
          value: scripts/casbin/
        - name: GIT_REPO_URL
          value: https://github.com/devtron-labs/devtron.git
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: casbin
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: 4ed6cdfcf6f13a93eb0c3c58d8b4f13292856960
        - name: GIT_BRANCH
          value: main
        envFrom:
          - secretRef:
              name: postgresql-migrator
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 1500
```
4. Delete the devtron pod once post this and login as super-admin.
