### ISSUE TITLE
Feature: BASE_PATH flag to expose devtron dashboard under a domain subpath url

### ISSUE THREAD

**Issue by OctavianHome** [devtron-labs/devtron#6139]
### 🔖 Feature description

Not always exposing the devtron dashboard to the root domain is the convenient one.
It would be great if it would exist a BASE_PATH environment variable or a basePath helm chart input variable so that by applying an ingress object the application would work under a domain subpath.
I tried to expose devtron dashboard into an AKS cluster under a domain subpath (like https://my.domain.com/devtron) but I was not able to make it working.

### 🎤 Pitch / Usecases

Not always exposing the devtron dashboard to the root domain is the convenient one.
Ideally an ingress resource like bellow should be enough to expose it under the domain subpath:
```
rules:
    - host: my.domain.com
      http:
        paths:
          - path: /devtron(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: devtron-service
                port:
                  number: 80
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)
