### ISSUE TITLE
Feature: Display Validation Error Messages on UI for Restricted Pod Exec Actions

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#6224]
### 🔖 Feature description

We have written ValidatingAdmissionPolicy to restrict any user exec in specific pods, which is working fine. Still, the error is not showing on UI as to why the user cannot exec into the pods.
Policy applied:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: block-postgres-exec
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CONNECT
        resourceNames:
          - postgresql-14-dcd-0
        resources:
          - pods/exec
        scope: "*"
  paramKind:
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingAdmissionPolicyBinding
  validations:
    - expression: "false"
      message: Exec is not allowed into postgres

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: block-postgres-exec-binding
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
  policyName: block-postgres-exec
  validationActions:
    - Deny
```

Please find the attached screenshot for reference
It throws the below error when we try using kubectl command.
<img width="1383" alt="Screenshot 2024-12-26 at 6 28 40 PM" src="https://github.com/user-attachments/assets/65bf18e5-c570-48be-ab67-3478ec2902fc" />

But on Devtron it only shows like this.
<img width="1071" alt="Screenshot 2024-12-26 at 6 29 45 PM" src="https://github.com/user-attachments/assets/1843fc06-08d1-4908-a489-fa22afbede6a" />

### 🎤 Pitch / Usecases

There should be visibility to users why they are not able to exec into the pods.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)
