### ISSUE TITLE
Bug: SSO Login Service configuration is misaligned and prevents saving

### ISSUE THREAD

**Issue by woopla** [devtron-labs/devtron#6312]
### 📜 Description

I just installed v1.0.0 using the Helm chart, and I cannot configure LDAP access. It seems to be because the YAML fields are misaligned:

![Image](https://github.com/user-attachments/assets/cdc0f5d1-12f7-43a1-8a6e-c6b8c7fe7d5b)

In all the examples I could see on your site, all the editable part is indented to be part of `config`.

### 👟 Reproduction steps

1. Go to _Global Configurations -> Authorization -> Login Services_
2. Edit the LDAP config
3. Click on "Save" (even using the default config)

### 👍 Expected behavior

Clicking on 'save' should save the config and allow me to login to Devtron using LDAP.

### 👎 Actual Behavior

I'm getting a "Some required fields are missing" error. I also tried to properly align with the fixed part above of the editable part, but it always snaps back to where it was.

### ☸ Kubernetes version

KFD-based cluster running Kubernetes v.1.29.3

### Cloud provider

<details>
On-prem KFD installation.
</details>

### 🌍 Browser

Edge

### 🧱 Your Environment

I tried with

- MS Edge 131.0.2903.112
- Google Chrome 131.0.6778.265
- Mozilla Firefox 

### ✅ Proposed Solution

You should either make sure that the editable fields are properly aligned, or make the whole section editable so this doesn't happen. I could have worked around the issue if I could align things myself...

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by pawan-mehta-dt** [comment]
@woopla can you confirm whether the final rended yaml after you save is correct for dex.config key in devtron-secret in devtroncd namespace?

**Comment by woopla** [comment]
@pawan-mehta-dt it's empty:
```bash
> k get -n devtroncd secret/devtron-secret -o jsonpath='{.data}' | jq '."dex.config"'
""
```

(I checked `k get -n devtroncd secret/devtron-secret -o yaml` to be sure, other things like `ADMIN_PASSWORD` are there as expected).

It's refusing to save the config because of this "missing" field.

**Comment by woopla** [comment]
@pawan-mehta-dt can you please share an example of a proper `dex.config` string, so I can try and set it manually in the secret?

**Comment by woopla** [comment]
@pawan-mehta-dt any example for me here?

**Comment by woopla** [comment]
I went ahead a created a YAML file, then shoved it into `dex.config` as a base64-encoded string. Nothing happens, I do not see anything in the UI. Either that field gets ignored, or errors preventing it from loading are ignored.

**Comment by pawan-mehta-dt** [comment]
```
  dex.config: |
    connectors:
    - config:
        bindDN: uid=admin,ou=people,dc=devtron,dc=local
        bindPW: ••••••••
        groupSearch:
          baseDN: ou=groups,dc=devtron,dc=local
          filter: (objectClass=groupOfUniqueNames)
          nameAttr: cn
          userMatchers:
            - groupAttr: member
              userAttr: DN
        host: lldap-service.devtron-demo:3890
        insecureNoSSL: true
        insecureSkipVerify: true
        userSearch:
          baseDN: ou=people,dc=devtron,dc=local
          emailAttr: mail
          idAttr: uid
          nameAttr: displayName
          preferredUsernameAttr: uid
          username: uid
        usernamePrompt: ••••••••
      id: ldap
      name: LDAP
      type: ldap
```
This is an example of Working dex config @woopla 
We can also schedule a call and debug the issue if you are stuck with it, fill a form with your work email and we'll schedule a call on the same to debug the issue.
https://oss-support.devtron.ai
