### ISSUE TITLE
bug(Deployment Chart): command.workingDir should be a string instead of a object

### ISSUE THREAD

**Issue by TGTGamer** [devtron-labs/devtron#6477]
https://github.com/devtron-labs/devtron/blob/d6d76fbcd8aa9ed483c5a97c975cc34b6ac90f81/scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/schema.json#L669-L674

should be: 

```json
 "workingDir": { 
   "type": "string", 
   "items": {}, 
   "description": "contains the working directory", 
   "title": "Working directory" 
 }
```
So that this works: 

```yml
command:
  enabled: true
  value:
    - sh
    - startup.sh
  workingDir: /string/to/path
```

Current error: 
Incorrect type. Expected "Working directory".yaml-schema: Working directory(0)
