### ISSUE TITLE
httpHeaders is not Supported in helm chart deployment  v3.12.0

### ISSUE THREAD

**Issue by sachincool** [devtron-labs/devtron#863]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

**To Reproduce**
* Add liveliness Probe /readiness probe with httpHeaders
Eg: 
```

LivenessProbe:
  Path: /
  port: 8080
  httpHeaders:
    - name: Host
      value: test.example.com
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  failureThreshold: 3
  ```

**Expected behavior**
```
livenessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: Host
                  value: test.navarc.co
 ```
**Current behavior** 
```
livenessProbe:
            httpGet:
              path: /
              port: 8080
```
describe what you currently experienced from this process, and thereby explain the bug

**Screenshots**

**Logs**
 
```
Paste any relevant application logs here.
```
